[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Rust utility functions provided by MaidSafe."
documentation = "http://docs.maidsafe.net/maidsafe_utilities/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "maidsafe_utilities"
readme = "README.md"
repository = "https://github.com/maidsafe/maidsafe_utilities"
version = "0.7.1"

[dependencies]
bincode = "~0.5.7"
clippy = {version = "~0.0.77", optional = true}
lazy_static = "~0.2.1"
log = "~0.3.6"
log4rs = "~0.3.3"
quick-error = "1.1.0"
rand = "~0.3.14"
regex = "~0.1.71"
rustc-serialize = "~0.3.19"
toml = "~0.1.30"
unwrap = "~1.1.0"
ws = "~0.5.0"
