[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Rust utility functions provided by MaidSafe."
documentation = "http://maidsafe.net/maidsafe_utilities/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "maidsafe_utilities"
readme = "README.md"
repository = "https://github.com/maidsafe/maidsafe_utilities"
version = "0.3.1"

[dependencies]
bincode = "~0.4.1"
clippy = {version = "~0.0.44", optional = true}
env_logger = "~0.3.2"
log = "~0.3.5"
rustc-serialize = "~0.3.18"
time = "~0.1.34"
quick-error = "1.0.0"
