[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Rust utility functions provided by MaidSafe."
documentation = "http://maidsafe.net/maidsafe_utilities/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "maidsafe_utilities"
readme = "README.md"
repository = "https://github.com/maidsafe/maidsafe_utilities"
version = "0.6.0"

[dependencies]
bincode = "~0.5.6"
clippy = {version = "~0.0.68", optional = true}
log = "~0.3.6"
log4rs = "~0.3.3"
net2 = "~0.2.23"
quick-error = "1.0.0"
rand = "~0.3.14"
regex = "~0.1.70"
rustc-serialize = "~0.3.19"
toml = "~0.1.30"
ws = "~0.4.7"
